homepage:
    path: /
    controller: App\Controller\HomeController::index
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
list_authors:
    path: /authors
    controller: App\Controller\AuthorController::listAuthors
view_author:
    path: '/authors/{id}/view'
    controller: App\Controller\AuthorController::viewAuthor
    methods: ['GET']
delete_author:
    path: '/authors/{id}'
    controller: App\Controller\AuthorController::deleteAuthor
    methods: ['GET']
delete_book:
    path: '/books/{id}/delete/{authorId}'
    controller: App\Controller\BookController::deleteBook
    methods: ['GET', 'POST']
add_book:
    path: /books/add
    controller: App\Controller\BookController::createBook
    methods: ['GET', 'POST']

